(()=>{'use strict';
const KEY='projekt-bau-v03',$=id=>document.getElementById(id),uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=load(),view='customers',editing=null,page=0,filters={};
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return{...x,customers:Array.isArray(x.customers)?x.customers:[],projects:Array.isArray(x.projects)?x.projects:[]}}catch(_){return{customers:[],projects:[]}}}
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const cname=c=>[c?.company,c?.firstName,c?.lastName].filter(Boolean).join(' · ')||c?.customer||'Kunde';
const customer=p=>state.customers.find(c=>c.id===p.customerId);
function toast(s){const x=$('toast');x.textContent=s;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function field(name,label,type='text',value='',wide=false,options=[]){const control=type==='textarea'?`<textarea name="${name}" rows="4">${esc(value)}</textarea>`:type==='select'?`<select name="${name}">${options.map(o=>`<option value="${esc(o.value)}" ${String(o.value)===String(value)?'selected':''}>${esc(o.label)}</option>`).join('')}</select>`:`<input name="${name}" type="${type}" value="${esc(value)}">`;return `<label class="${wide?'wide':''}"><span>${label}</span>${control}</label>`}
const cols=[['number','NUMMER'],['company','FIRMA'],['lastName','NACHNAME'],['firstName','VORNAME'],['phone','TELEFON'],['mobile','MOBIL'],['street','STRASSE'],['zip','ZIP'],['city','STADT'],['email','E-MAIL']];
function render(){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('customersView').classList.toggle('hidden',view!=='customers');$('projectsView').classList.toggle('hidden',view!=='projects');
$('customerHeaders').innerHTML=cols.map(([,label])=>`<th><span class="sort">◇</span> ${label}</th>`).join('');$('customerFilters').innerHTML=cols.map(([key])=>`<th><input data-filter="${key}" value="${esc(filters[key]||'')}" aria-label="${key} filtern" placeholder="▽"></th>`).join('');let cs=state.customers.filter(c=>cols.every(([key])=>String(c[key]||'').toLowerCase().includes((filters[key]||'').toLowerCase())));const size=Number($('pageSize').value),slice=cs.slice(page*size,(page+1)*size);$('customerList').innerHTML=slice.map(c=>`<tr data-customer="${esc(c.id)}">${cols.map(([key])=>`<td>${esc(c[key]||'')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="10" class="empty">Noch keine Kunden vorhanden.</td></tr>`;$('firstPage').disabled=$('prevPage').disabled=page===0;$('nextPage').disabled=(page+1)*size>=cs.length;document.querySelectorAll('[data-filter]').forEach(i=>i.oninput=()=>{filters[i.dataset.filter]=i.value;page=0;render()});
const q=$('search').value.trim().toLowerCase(),ps=state.projects.filter(p=>JSON.stringify(p).toLowerCase().includes(q)||cname(customer(p)).toLowerCase().includes(q));$('projectList').innerHTML=ps.map(p=>`<button class="card" data-project="${esc(p.id)}"><span class="tag">${esc(p.projectNo||'PROJEKT')}</span><h3>${esc(p.name||'Projekt ohne Namen')}</h3><p>${esc(cname(customer(p))||p.customer||'Kein Kunde')}</p><small>${esc(p.address||p.status||'Keine Adresse')}</small></button>`).join('')||'<p class="empty">Noch keine Projekte vorhanden.</p>';document.querySelectorAll('[data-customer]').forEach(b=>b.onclick=()=>openCustomer(b.dataset.customer));document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.project))}
function show(canDelete){$('deleteItem').classList.toggle('hidden',!canDelete);$('editor').showModal()}
function openCustomer(id=''){const c=state.customers.find(x=>x.id===id)||{};editing={type:'customer',id};$('editorTitle').textContent=id?'Kunde bearbeiten':'Neuer Kunde';$('editorFields').innerHTML=field('number','Kundennummer','text',c.number)+field('company','Firma','text',c.company)+field('firstName','Vorname','text',c.firstName)+field('lastName','Nachname','text',c.lastName)+field('street','Strasse','text',c.street,true)+field('zip','PLZ','text',c.zip)+field('city','Ort','text',c.city)+field('phone','Telefon','tel',c.phone)+field('mobile','Mobil','tel',c.mobile)+field('email','E-Mail','email',c.email,true)+field('notes','Notizen','textarea',c.notes,true);show(!!id)}
function openProject(id=''){const p=state.projects.find(x=>x.id===id)||{},opts=[{value:'',label:'Kunde auswählen …'},...state.customers.map(c=>({value:c.id,label:cname(c)}))];editing={type:'project',id};$('editorTitle').textContent=id?'Projekt bearbeiten':'Neues Projekt';$('editorFields').innerHTML=field('projectNo','Projektnummer','text',p.projectNo)+field('name','Projektname','text',p.name)+field('customerId','Kunde','select',p.customerId||'',true,opts)+field('address','Objektadresse','text',p.address,true)+field('status','Status','select',p.status||'Aktiv',false,['Anfrage','Aktiv','Pausiert','Abgeschlossen'].map(x=>({value:x,label:x})))+field('owner','Projektleiter','text',p.owner)+field('description','Beschreibung','textarea',p.description,true);show(!!id)}
$('editorForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(editing.type==='customer'){if(!data.company&&!data.firstName&&!data.lastName)return alert('Bitte Firma oder Name eingeben.');const old=state.customers.find(x=>x.id===editing.id),item={...old,...data,id:old?.id||uid(),updatedAt:new Date().toISOString()};old?Object.assign(old,item):state.customers.unshift(item)}else{if(!data.name)return alert('Bitte Projektname eingeben.');const old=state.projects.find(x=>x.id===editing.id),item={...old,...data,customer:cname(state.customers.find(c=>c.id===data.customerId)),id:old?.id||uid(),updatedAt:new Date().toISOString()};old?Object.assign(old,item):state.projects.unshift(item)}save();$('editor').close();render();toast('Gespeichert.')});
$('deleteItem').onclick=()=>{if(!confirm('Eintrag wirklich löschen?'))return;if(editing.type==='customer'){if(state.projects.some(p=>p.customerId===editing.id))return alert('Dieser Kunde ist mit Projekten verbunden und kann nicht gelöscht werden.');state.customers=state.customers.filter(x=>x.id!==editing.id)}else state.projects=state.projects.filter(x=>x.id!==editing.id);save();$('editor').close();render();toast('Gelöscht.')};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('newCustomer').onclick=()=>openCustomer();$('newProject').onclick=()=>openProject();$('search').oninput=render;$('pageSize').onchange=()=>{page=0;render()};$('firstPage').onclick=()=>{page=0;render()};$('prevPage').onclick=()=>{page=Math.max(0,page-1);render()};$('nextPage').onclick=()=>{page++;render()};$('customerHelp').onclick=()=>alert('Kunden filtern: Trichtersymbol-Zeile verwenden. Kunde bearbeiten: Tabellenzeile anklicken.');$('customerExport').onclick=()=>{const csv=[cols.map(x=>x[1]),...state.customers.map(c=>cols.map(([k])=>c[k]||''))].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='Kunden.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
