(()=>{'use strict';
const KEY='projekt-bau-v03',$=id=>document.getElementById(id),uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const USER='Vakkas',DEFAULT_CHANNELS=['hausheld.ch','BNI','Internet','Soziale Medien','homedeal.ch','Empfehlung bestehende Kunden','Bestehende Kunde'],customerFields=['type','number','salutation','letterSalutation','firstName','lastName','email','fax','phone','mobile','addressLabel','addressType','addressRecipient','addressFirstName','addressLastName','addressPhone','addressEmail','addressExtra','street','houseNumber','zip','city','accountHolder','bankName','iban','bic','paymentTerm','discountEnabled','reverseCharge','notes','acquisitionChannel','language'],contactFields=['contactSalutation','contactLetterSalutation','contactTitle','contactFirstName','contactLastName','contactBirthday','contactRole','contactEmail','contactFax','contactPhone','contactMobile','contactPrivatePhone','contactNotes'],labels={type:'Typ',number:'Kundennummer',salutation:'Anrede',letterSalutation:'Briefanrede',firstName:'Vorname',lastName:'Nachname',email:'Email',fax:'Fax',phone:'Telefon',mobile:'Mobil',addressLabel:'Adressbezeichnung',addressType:'Adresstyp',addressRecipient:'Abweichender Empfänger',addressFirstName:'Adress-Vorname',addressLastName:'Adress-Nachname',addressPhone:'Adress-Telefon',addressEmail:'Adress-Email',addressExtra:'Adressergänzung',street:'Strasse',houseNumber:'Hausnummer',zip:'PLZ',city:'Stadt',accountHolder:'Kontoinhaber',bankName:'Bank Name',iban:'IBAN',bic:'BIC',paymentTerm:'Zahlungsziel',discountEnabled:'Skonto',reverseCharge:'Reverse Charge',notes:'Anmerkung',acquisitionChannel:'Akquisekanal',language:'Sprache'};
customerFields.push('company','vatNumber');Object.assign(labels,{company:'Name',vatNumber:'Mehrwertsteuernummer'});
let state=load(),view='customers',editing=null,page=0,filters={};state.customers.forEach(c=>{if(c.type==='Privatkunde')c.type='Privat'});
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return{...x,customers:Array.isArray(x.customers)?x.customers:[],projects:Array.isArray(x.projects)?x.projects:[]}}catch(_){return{customers:[],projects:[]}}}
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)),now=()=>new Date().toISOString(),cname=c=>[c?.company,c?.firstName,c?.lastName].filter(Boolean).join(' · ')||c?.customer||'Kunde',customer=p=>state.customers.find(c=>c.id===p.customerId);
function toast(s){const x=$('toast');x.textContent=s;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function nextNumber(){const y=new Date().getFullYear(),max=state.customers.reduce((m,c)=>{const a=String(c.number||'').match(new RegExp(`^K-${y}-(\\d+)$`));return Math.max(m,a?Number(a[1]):0)},0);return `K-${y}-${String(max+1).padStart(3,'0')}`}
function field(name,label,type='text',value='',wide=false,options=[]){const control=type==='textarea'?`<textarea name="${name}" rows="4">${esc(value)}</textarea>`:type==='select'?`<select name="${name}">${options.map(o=>`<option value="${esc(o.value)}" ${String(o.value)===String(value)?'selected':''}>${esc(o.label)}</option>`).join('')}</select>`:`<input name="${name}" type="${type}" value="${esc(value)}">`;return `<label class="${wide?'wide':''}"><span>${label}</span>${control}</label>`}
const cols=[['number','NUMMER'],['company','FIRMA'],['lastName','NACHNAME'],['firstName','VORNAME'],['phone','TELEFON'],['mobile','MOBIL'],['street','STRASSE'],['zip','ZIP'],['city','STADT'],['email','E-MAIL']];
function render(){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===(view==='customerEditor'?'customers':view)));$('customersView').classList.toggle('hidden',view!=='customers');$('customerEditorView').classList.toggle('hidden',view!=='customerEditor');$('projectsView').classList.toggle('hidden',view!=='projects');
$('customerHeaders').innerHTML=cols.map(([,l])=>`<th><span class="sort">◇</span> ${l}</th>`).join('');$('customerFilters').innerHTML=cols.map(([k])=>`<th><input data-filter="${k}" value="${esc(filters[k]||'')}" aria-label="${k} filtern" placeholder="▽"></th>`).join('');let cs=state.customers.filter(c=>!c.deletedAt&&cols.every(([k])=>String(c[k]||'').toLowerCase().includes((filters[k]||'').toLowerCase()))),size=Number($('pageSize').value),slice=cs.slice(page*size,(page+1)*size);$('customerList').innerHTML=slice.map(c=>`<tr data-customer="${esc(c.id)}">${cols.map(([k])=>`<td>${esc(c[k]||'')}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="10" class="empty">Noch keine Kunden vorhanden.</td></tr>';$('firstPage').disabled=$('prevPage').disabled=page===0;$('nextPage').disabled=(page+1)*size>=cs.length;document.querySelectorAll('[data-filter]').forEach(i=>i.oninput=()=>{filters[i.dataset.filter]=i.value;page=0;render()});
const q=$('search').value.trim().toLowerCase(),ps=state.projects.filter(p=>JSON.stringify(p).toLowerCase().includes(q)||cname(customer(p)).toLowerCase().includes(q));$('projectList').innerHTML=ps.map(p=>`<button class="card" data-project="${esc(p.id)}"><span class="tag">${esc(p.projectNo||'PROJEKT')}</span><h3>${esc(p.name||'Projekt ohne Namen')}</h3><p>${esc(cname(customer(p))||p.customer||'Kein Kunde')}</p><small>${esc(p.address||p.status||'Keine Adresse')}</small></button>`).join('')||'<p class="empty">Noch keine Projekte vorhanden.</p>';document.querySelectorAll('[data-customer]').forEach(b=>b.onclick=()=>openCustomer(b.dataset.customer));document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.project))}
function renderHistory(c){const events=[...(c.history||[])].reverse();$('customerHistory').innerHTML=events.length?events.map(e=>`<article><div><strong>${esc(e.action)}</strong><time>${esc(new Date(e.at).toLocaleString('de-CH'))}</time></div><p>${esc(e.detail||'')}</p><small>von ${esc(e.user||USER)}</small></article>`).join(''):`<div class="history-columns"><div><span>Erstellt am</span><strong>–</strong><small>von –</small></div><div><span>Geändert am</span><strong>–</strong><small>von –</small></div><div><span>Gelöscht am</span><strong>–</strong><small>von –</small></div></div>`}
function renderCustomerExtras(c){$('fileList').innerHTML=(c.files||[]).map(x=>`<div class="file-row"><span>▱ ${esc(x.name)}</span><small>${esc(x.size)} · ${esc(new Date(x.at).toLocaleString('de-CH'))}</small></div>`).join('');$('customerDocuments').innerHTML=state.projects.filter(p=>p.customerId===c.id).map(p=>`<div class="file-row"><span>▤ ${esc(p.projectNo||'')} ${esc(p.name||'Projekt')}</span><small>${esc(p.status||'')}</small></div>`).join('')}
function logCustomer(c,action,detail){c.history=[...(c.history||[]),{at:now(),user:USER,action,detail}];save();renderHistory(c)}
function renderChannels(){state.acquisitionChannels=[...new Set([...(state.acquisitionChannels||[]),...DEFAULT_CHANNELS])];$('acquisitionChannels').innerHTML=state.acquisitionChannels.map(x=>`<option value="${esc(x)}">`).join('')}
function renderContacts(c,selected=''){const s=$('contactSelection');s.innerHTML='<option value="">Neuer Ansprechpartner</option>'+((c.contacts||[]).map(x=>`<option value="${esc(x.id)}">${esc([x.contactFirstName,x.contactLastName,x.contactRole].filter(Boolean).join(' · ')||'Ansprechpartner')}</option>`).join(''));s.value=selected}
function fillContact(x={}){const f=$('customerPageForm');contactFields.forEach(k=>{if(f.elements[k])f.elements[k].value=x[k]||''})}
function toggleCompany(){const isCompany=$('customerPageForm').elements.type.value==='Firma';document.querySelectorAll('.company-only').forEach(x=>x.classList.toggle('hidden',!isCompany))}
function openCustomer(id=''){const c=state.customers.find(x=>x.id===id)||{number:nextNumber(),history:[],files:[],contacts:[]};if(id&&!c.history?.length)c.history=[{at:c.createdAt||c.updatedAt||now(),user:c.createdBy||c.updatedBy||USER,action:'Kunde erstellt',detail:`Kundennummer ${c.number||'–'} (bestehender Datensatz)`}];editing={type:'customer',id,original:{...c},contactId:''};const f=$('customerPageForm');customerFields.forEach(k=>{if(!f.elements[k])return;if(f.elements[k].type==='checkbox')f.elements[k].checked=!!c[k];else f.elements[k].value=c[k]||''});fillContact();renderContacts(c);renderChannels();toggleCompany();$('deleteCustomer').classList.toggle('hidden',!id);renderHistory(c);renderCustomerExtras(c);view='customerEditor';render()}
function saveCustomer(){const f=$('customerPageForm'),data=Object.fromEntries(new FormData(f));data.discountEnabled=f.elements.discountEnabled.checked;data.reverseCharge=f.elements.reverseCharge.checked;if(data.type==='Firma'&&!data.company)return alert('Bitte den Firmennamen eingeben.');if(data.type!=='Firma'&&!data.firstName&&!data.lastName)return alert('Bitte Vorname oder Nachname eingeben.');let c=state.customers.find(x=>x.id===editing.id);if(!c){const at=now();c={...data,id:uid(),createdAt:at,createdBy:USER,history:[{at,user:USER,action:'Kunde erstellt',detail:`Kundennummer ${data.number}`} ]};state.customers.unshift(c);editing.id=c.id}else{const changes=customerFields.filter(k=>String(c[k]??'')!==String(data[k]??'')).map(k=>`${labels[k]}: „${c[k]??'–'}“ → „${data[k]??'–'}“`);Object.assign(c,data,{updatedAt:now(),updatedBy:USER});if(changes.length)c.history=[...(c.history||[]),{at:c.updatedAt,user:USER,action:'Kunde geändert',detail:changes.join(' · ')}]}
saveCurrentContact(c,true);c.documentDefaults={...(c.documentDefaults||{}),paymentTermDays:Number(data.paymentTerm||0),discountEnabled:!!data.discountEnabled,reverseCharge:!!data.reverseCharge};save();renderHistory(c);renderContacts(c,editing.contactId);toast('Kunde gespeichert.')}
function show(canDelete){$('deleteItem').classList.toggle('hidden',!canDelete);$('editor').showModal()}
function openProject(id=''){const p=state.projects.find(x=>x.id===id)||{},opts=[{value:'',label:'Kunde auswählen …'},...state.customers.filter(c=>!c.deletedAt).map(c=>({value:c.id,label:cname(c)}))];editing={type:'project',id};$('editorTitle').textContent=id?'Projekt bearbeiten':'Neues Projekt';$('editorFields').innerHTML=field('projectNo','Projektnummer','text',p.projectNo)+field('name','Projektname','text',p.name)+field('customerId','Kunde','select',p.customerId||'',true,opts)+field('address','Objektadresse','text',p.address,true)+field('status','Status','select',p.status||'Aktiv',false,['Anfrage','Aktiv','Pausiert','Abgeschlossen'].map(x=>({value:x,label:x})))+field('owner','Projektleiter','text',p.owner)+field('description','Beschreibung','textarea',p.description,true);show(!!id)}
$('customerPageForm').onsubmit=e=>{e.preventDefault();saveCustomer()};$('backCustomers').onclick=()=>{view='customers';render()};$('deleteCustomer').onclick=()=>{const c=state.customers.find(x=>x.id===editing.id);if(!c||!confirm('Kunde wirklich löschen?'))return;if(state.projects.some(p=>p.customerId===c.id))return alert('Dieser Kunde ist mit Projekten verbunden und kann nicht gelöscht werden.');c.deletedAt=now();c.deletedBy=USER;c.history=[...(c.history||[]),{at:c.deletedAt,user:USER,action:'Kunde gelöscht',detail:'Kundendatensatz wurde gelöscht.'}];save();view='customers';render();toast('Kunde gelöscht.')};
$('editorForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(!data.name)return alert('Bitte Projektname eingeben.');const old=state.projects.find(x=>x.id===editing.id),item={...old,...data,customer:cname(state.customers.find(c=>c.id===data.customerId)),id:old?.id||uid(),updatedAt:now()};old?Object.assign(old,item):state.projects.unshift(item);save();$('editor').close();render();toast('Gespeichert.')});$('deleteItem').onclick=()=>{if(!confirm('Projekt wirklich löschen?'))return;state.projects=state.projects.filter(x=>x.id!==editing.id);save();$('editor').close();render();toast('Gelöscht.')};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('newCustomer').onclick=()=>openCustomer();$('newProject').onclick=()=>openProject();$('search').oninput=render;$('pageSize').onchange=()=>{page=0;render()};$('firstPage').onclick=()=>{page=0;render()};$('prevPage').onclick=()=>{page=Math.max(0,page-1);render()};$('nextPage').onclick=()=>{page++;render()};$('customerHelp').onclick=$('customerFormHelp').onclick=()=>alert('Kundendaten eingeben und mit dem Stift- oder Speichern-Knopf sichern. Alle Änderungen erscheinen im Verlauf.');document.querySelectorAll('[data-contact]').forEach(b=>b.onclick=()=>{const v=$('customerPageForm').elements[b.dataset.contact].value.trim();if(!v)return;b.dataset.contact==='email'?location.href=`mailto:${v}`:location.href=`tel:${v}`});$('customerExport').onclick=()=>{const csv=[cols.map(x=>x[1]),...state.customers.filter(c=>!c.deletedAt).map(c=>cols.map(([k])=>c[k]||''))].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='Kunden.csv';a.click()};render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
document.querySelectorAll('[data-customer-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-customer-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-tab-pane]').forEach(x=>x.classList.toggle('hidden',x.dataset.tabPane!==b.dataset.customerTab))});document.querySelectorAll('#documentTabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#documentTabs button').forEach(x=>x.classList.toggle('active',x===b));const c=state.customers.find(x=>x.id===editing?.id);if(c)logCustomer(c,'Dokumentenregister geöffnet',b.textContent.trim())});const fileInput=$('customerFiles'),pickFiles=()=>fileInput.click();$('selectFiles').onclick=pickFiles;$('fileDropzone').onclick=pickFiles;$('fileDropzone').ondragover=e=>e.preventDefault();$('fileDropzone').ondrop=e=>{e.preventDefault();addFiles(e.dataTransfer.files)};fileInput.onchange=()=>addFiles(fileInput.files);function addFiles(files){let c=state.customers.find(x=>x.id===editing?.id);if(!c)return alert('Bitte Kunde zuerst speichern.');const added=[...files].map(f=>({id:uid(),name:f.name,size:`${Math.ceil(f.size/1024)} KB`,type:f.type,at:now()}));c.files=[...(c.files||[]),...added];logCustomer(c,'Datei hinzugefügt',added.map(x=>x.name).join(', '));renderCustomerExtras(c);fileInput.value=''}$('addDocument').onclick=()=>{const c=state.customers.find(x=>x.id===editing?.id);if(!c)return alert('Bitte Kunde zuerst speichern.');const type=document.querySelector('#documentTabs button.active')?.textContent.trim()||'Dokument';logCustomer(c,'Dokument angelegt',type);toast(`${type}: Neuer Eintrag protokolliert.`)};
function saveCurrentContact(c,silent=false){const f=$('customerPageForm'),data={};contactFields.forEach(k=>data[k]=f.elements[k]?.value||'');if(!contactFields.some(k=>data[k]))return false;c.contacts=Array.isArray(c.contacts)?c.contacts:[];let x=c.contacts.find(x=>x.id===editing.contactId),action='Ansprechpartner geändert';if(x)Object.assign(x,data,{updatedAt:now()});else{x={...data,id:uid(),createdAt:now()};c.contacts.push(x);editing.contactId=x.id;action='Ansprechpartner erstellt'}const detail=[data.contactFirstName,data.contactLastName,data.contactRole].filter(Boolean).join(' · ');if(silent)c.history=[...(c.history||[]),{at:now(),user:USER,action,detail}];else logCustomer(c,action,detail);renderContacts(c,x.id);return true}
$('contactSelection').onchange=e=>{const c=state.customers.find(x=>x.id===editing?.id),x=c?.contacts?.find(x=>x.id===e.target.value);editing.contactId=x?.id||'';fillContact(x)};$('newContact').onclick=()=>{const c=state.customers.find(x=>x.id===editing?.id);if(c)saveCurrentContact(c);editing.contactId='';fillContact();$('contactSelection').value=''};$('deleteContact').onclick=()=>{const c=state.customers.find(x=>x.id===editing?.id),x=c?.contacts?.find(x=>x.id===editing.contactId);if(!x||!confirm('Ansprechpartner wirklich löschen?'))return;c.contacts=c.contacts.filter(y=>y.id!==x.id);logCustomer(c,'Ansprechpartner gelöscht',[x.contactFirstName,x.contactLastName].filter(Boolean).join(' '));editing.contactId='';fillContact();renderContacts(c)};
$('addAcquisitionChannel').onclick=()=>{const input=$('customerPageForm').elements.acquisitionChannel;let value=input.value.trim()||prompt('Neuen Akquisekanal eingeben:')?.trim();if(!value)return;state.acquisitionChannels=[...new Set([...(state.acquisitionChannels||[]),value])];save();renderChannels();input.value=value;const c=state.customers.find(x=>x.id===editing?.id);if(c)logCustomer(c,'Akquisekanal hinzugefügt',value)};
let addressTimer;const street=$('customerPageForm').elements.street,suggestions=$('addressSuggestions');street.oninput=()=>{clearTimeout(addressTimer);const q=street.value.trim();if(q.length<3){suggestions.classList.add('hidden');return}addressTimer=setTimeout(async()=>{try{const url='https://api3.geo.admin.ch/rest/services/ech/MapServer/find?layer=ch.swisstopo.amtliches-strassenverzeichnis&searchField=stn_label&returnGeometry=false&contains=true&searchText='+encodeURIComponent(q);const data=await fetch(url).then(r=>r.json()),items=(data.results||[]).slice(0,8);suggestions.innerHTML=items.map((x,i)=>`<button type="button" data-address-i="${i}"><strong>${esc(x.attributes?.stn_label||x.attributes?.label||'')}</strong><small>${esc(x.attributes?.zip_label||'')}</small></button>`).join('');suggestions.classList.toggle('hidden',!items.length);suggestions.querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=items[Number(b.dataset.addressI)].attributes||{},zip=String(a.zip_label||'').match(/^(\d{4})\s+(.+)$/);street.value=a.stn_label||a.label||q;if(zip){$('customerPageForm').elements.zip.value=zip[1];$('customerPageForm').elements.city.value=zip[2]}suggestions.classList.add('hidden')})}catch(_){suggestions.classList.add('hidden')}},280)};document.addEventListener('click',e=>{if(!e.target.closest('.street-field'))suggestions.classList.add('hidden')});
$('customerPageForm').elements.type.onchange=toggleCompany;$('vatHelp').onclick=()=>alert('Mehrwertsteuernummer im Format CHE-123.456.789 MWST eingeben.');
})();
