(()=>{'use strict';
const $=id=>document.getElementById(id), modal=$('photoDocModal'), canvas=$('photoCanvas'); if(!modal||!canvas)return; const ctx=canvas.getContext('2d');
let base=null, baseDataURL='', tool='select', objects=[], selected=-1, drawing=null, history=[], future=[], filter={brightness:100,contrast:100,saturation:100,sharpness:0}, editingPhoto=null, editingArea=null;
const key='projektbau_photo_docs_v270';
function project(){try{return typeof cur==='function'?cur():null}catch(_){return null}}
function fillAreas(){const s=$('photoArea');if(!s)return;const p=project();const old=s.value;s.innerHTML='<option value="">Allgemeine Projektdokumentation</option>'+((p&&p.areas)||[]).map(a=>`<option value="${a.id}">${String(a.name||'Bereich').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}</option>`).join('');if([...s.options].some(o=>o.value===old))s.value=old}
function snap(){history.push(JSON.stringify({objects,filter,baseDataURL,title:$('photoTitle').value,note:$('photoNote').value}));if(history.length>40)history.shift();future=[]}
function restore(s){const x=JSON.parse(s);objects=x.objects||[];filter=x.filter||filter;$('photoTitle').value=x.title||'';$('photoNote').value=x.note||'';['brightness','contrast','saturation','sharpness'].forEach(k=>{$('photo'+k[0].toUpperCase()+k.slice(1)).value=filter[k]});if(x.baseDataURL&&x.baseDataURL!==baseDataURL)loadURL(x.baseDataURL,false);else render();updateVals()}
function loadURL(url,doSnap=true){const im=new Image();im.onload=()=>{base=im;baseDataURL=url;const max=2200,scale=Math.min(1,max/Math.max(im.naturalWidth,im.naturalHeight));canvas.width=Math.round(im.naturalWidth*scale);canvas.height=Math.round(im.naturalHeight*scale);$('photoEmpty').style.display='none';objects=[];selected=-1;if(doSnap)snap();render()};im.src=url}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);if(!base)return;ctx.save();ctx.filter=`brightness(${filter.brightness}%) contrast(${filter.contrast}%) saturate(${filter.saturation}%)`;ctx.drawImage(base,0,0,canvas.width,canvas.height);ctx.restore();objects.forEach((o,i)=>drawObject(o,i===selected));if(drawing)drawObject(drawing,false)}
function drawObject(o,sel){ctx.save();ctx.strokeStyle=o.color;ctx.fillStyle=o.color;ctx.lineWidth=o.width;ctx.lineCap='round';ctx.lineJoin='round';if(o.type==='pen'){ctx.beginPath();o.pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}else if(o.type==='line'||o.type==='arrow'){ctx.beginPath();ctx.moveTo(o.x1,o.y1);ctx.lineTo(o.x2,o.y2);ctx.stroke();if(o.type==='arrow'){const a=Math.atan2(o.y2-o.y1,o.x2-o.x1),l=14+o.width*2;ctx.beginPath();ctx.moveTo(o.x2,o.y2);ctx.lineTo(o.x2-l*Math.cos(a-.5),o.y2-l*Math.sin(a-.5));ctx.lineTo(o.x2-l*Math.cos(a+.5),o.y2-l*Math.sin(a+.5));ctx.closePath();ctx.fill()}}else if(o.type==='rect')ctx.strokeRect(o.x,o.y,o.w,o.h);else if(o.type==='ellipse'){ctx.beginPath();ctx.ellipse(o.x+o.w/2,o.y+o.h/2,Math.abs(o.w/2),Math.abs(o.h/2),0,0,Math.PI*2);ctx.stroke()}else if(o.type==='text'){ctx.font=`700 ${o.font}px Arial`;ctx.fillText(o.text,o.x,o.y)}if(sel){const b=bounds(o);ctx.strokeStyle='#2563eb';ctx.lineWidth=1;ctx.setLineDash([6,4]);ctx.strokeRect(b.x-6,b.y-6,b.w+12,b.h+12)}ctx.restore()}
function bounds(o){if(o.type==='text'){ctx.font=`700 ${o.font}px Arial`;return{x:o.x,y:o.y-o.font,w:ctx.measureText(o.text).width,h:o.font*1.2}}if(o.type==='pen'){const xs=o.pts.map(p=>p.x),ys=o.pts.map(p=>p.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}if(o.x1!=null)return{x:Math.min(o.x1,o.x2),y:Math.min(o.y1,o.y2),w:Math.abs(o.x2-o.x1),h:Math.abs(o.y2-o.y1)};return{x:Math.min(o.x,o.x+o.w),y:Math.min(o.y,o.y+o.h),w:Math.abs(o.w),h:Math.abs(o.h)}}
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function hit(p){for(let i=objects.length-1;i>=0;i--){const b=bounds(objects[i]);if(p.x>=b.x-12&&p.x<=b.x+b.w+12&&p.y>=b.y-12&&p.y<=b.y+b.h+12)return i}return-1}
canvas.addEventListener('pointerdown',e=>{if(!base)return;canvas.setPointerCapture(e.pointerId);const p=pos(e);if(tool==='select'){selected=hit(p);if(selected>=0)drawing={move:true,start:p,orig:JSON.parse(JSON.stringify(objects[selected]))};render();return}snap();const common={color:$('photoColor').value,width:+$('photoWidth').value};if(tool==='text'){const text=prompt('Text eingeben:');if(text){objects.push({type:'text',text,x:p.x,y:p.y,font:+$('photoFontSize').value,...common});selected=objects.length-1;render()}return}if(tool==='pen')drawing={type:'pen',pts:[p],...common};else drawing={type:tool,x1:p.x,y1:p.y,x2:p.x,y2:p.y,x:p.x,y:p.y,w:0,h:0,...common}});
canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=pos(e);if(drawing.move){const dx=p.x-drawing.start.x,dy=p.y-drawing.start.y,o=objects[selected],z=drawing.orig;if(z.type==='text'){o.x=z.x+dx;o.y=z.y+dy}else if(z.type==='pen')o.pts=z.pts.map(q=>({x:q.x+dx,y:q.y+dy}));else if(z.x1!=null){o.x1=z.x1+dx;o.x2=z.x2+dx;o.y1=z.y1+dy;o.y2=z.y2+dy}else{o.x=z.x+dx;o.y=z.y+dy}render();return}if(drawing.type==='pen')drawing.pts.push(p);else{drawing.x2=p.x;drawing.y2=p.y;drawing.w=p.x-drawing.x;drawing.h=p.y-drawing.y}render()});
canvas.addEventListener('pointerup',()=>{if(!drawing)return;if(drawing.move){snap();drawing=null;return}objects.push(drawing);selected=objects.length-1;drawing=null;render()});
document.querySelectorAll('[data-photo-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.photoTool;document.querySelectorAll('[data-photo-tool]').forEach(x=>x.classList.toggle('active',x===b))});
$('photoInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>loadURL(r.result);r.readAsDataURL(f)};
function updateVals(){['Brightness','Contrast','Saturation','Sharpness'].forEach(k=>{$('photo'+k+'Val').textContent=$('photo'+k).value+(k==='Sharpness'?'':'%')})}
['brightness','contrast','saturation','sharpness'].forEach(k=>{$('photo'+k[0].toUpperCase()+k.slice(1)).oninput=e=>{filter[k]=+e.target.value;updateVals();render()}});
$('photoUndo').onclick=()=>{if(history.length<2)return;future.push(history.pop());restore(history[history.length-1])};$('photoRedo').onclick=()=>{if(!future.length)return;const s=future.pop();history.push(s);restore(s)};
$('photoDeleteSelected').onclick=()=>{if(selected<0)return;snap();objects.splice(selected,1);selected=-1;render()};$('photoReset').onclick=()=>{if(!base)return;snap();objects=[];filter={brightness:100,contrast:100,saturation:100,sharpness:0};updateVals();render()};
function rotate(dir){if(!base)return;const t=document.createElement('canvas');t.width=canvas.height;t.height=canvas.width;const x=t.getContext('2d');x.translate(t.width/2,t.height/2);x.rotate(dir*Math.PI/2);x.drawImage(canvas,-canvas.width/2,-canvas.height/2);loadURL(t.toDataURL('image/jpeg',.94))}$('photoRotateLeft').onclick=()=>rotate(-1);$('photoRotateRight').onclick=()=>rotate(1);
$('photoCropToggle').onclick=()=>{if(!base)return;alert('Zuschneiden: Mit Rechteck den gewünschten Bereich markieren; danach wird diese Funktion in der nächsten Stufe als nicht-destruktiver Crop-Griff erweitert.')};
function output(){selected=-1;render();return canvas.toDataURL('image/jpeg',.94)}
function gallery(){const a=JSON.parse(localStorage.getItem(key)||'[]'),g=$('photoGallery');g.innerHTML=a.map((x,i)=>`<div class="photo-thumb" data-i="${i}"><img src="${x.image}"><small>${x.title||'Projektfoto'}</small></div>`).join('');g.querySelectorAll('.photo-thumb').forEach(el=>el.onclick=()=>{const x=a[+el.dataset.i];$('photoTitle').value=x.title||'';$('photoNote').value=x.note||'';loadURL(x.image)})}
$('photoSave').onclick=()=>{if(!base)return;const rendered=output();if(editingPhoto){editingPhoto.title=$('photoTitle').value.trim();editingPhoto.note=$('photoNote').value.trim();editingPhoto.data=rendered;editingPhoto.image=rendered;editingPhoto.editedAt=new Date().toISOString();if(typeof save==='function')save();editingPhoto=null;editingArea=null;alert('Fotoänderungen wurden im Projekt gespeichert.');gallery();return;}const item={id:(typeof u==='function'?u():String(Date.now())),title:$('photoTitle').value.trim(),note:$('photoNote').value.trim(),data:rendered,image:rendered,kind:'Fotodokumentation',date:new Date().toISOString()};const p=project(),areaId=$('photoArea')?.value;if(p&&areaId){const ar=(p.areas||[]).find(x=>String(x.id)===String(areaId));if(ar){ar.photos=ar.photos||[];ar.photos.unshift({...item});if(typeof save==='function')save();alert('Foto wurde im gewählten Bereich gespeichert und kann im PDF-Bericht verwendet werden.')}}else{const a=JSON.parse(localStorage.getItem(key)||'[]');a.unshift(item);localStorage.setItem(key,JSON.stringify(a.slice(0,50)));alert('Foto wurde in der Projektdokumentation gespeichert.')}gallery()};
$('photoExportJpg').onclick=()=>{if(!base)return;const a=document.createElement('a');a.href=output();a.download=($('photoTitle').value||'Projektfoto').replace(/[^a-z0-9äöüß_-]+/gi,'_')+'.jpg';a.click()};
$('photoExportPdf').onclick=()=>{if(!base)return;const J=window.jspdf?.jsPDF;if(!J)return;const pdf=new J({orientation:canvas.width>canvas.height?'landscape':'portrait',unit:'mm',format:'a4'}),pw=pdf.internal.pageSize.getWidth(),ph=pdf.internal.pageSize.getHeight();pdf.setFontSize(16);pdf.text($('photoTitle').value||'Fotodokumentation',14,16);const img=output(),ratio=canvas.width/canvas.height,maxW=pw-28,maxH=ph-55;let w=maxW,h=w/ratio;if(h>maxH){h=maxH;w=h*ratio}pdf.addImage(img,'JPEG',14,25,w,h);const note=$('photoNote').value;if(note){pdf.setFontSize(10);pdf.text(pdf.splitTextToSize(note,pw-28),14,32+h)}pdf.save('Fotodokumentation.pdf')};
function open(){editingPhoto=null;editingArea=null;modal.classList.remove('hidden');modal.setAttribute('aria-hidden','false');fillAreas();gallery()}function openExisting(ph,area){editingPhoto=ph;editingArea=area||null;modal.classList.remove('hidden');modal.setAttribute('aria-hidden','false');fillAreas();if(area&&$('photoArea'))$('photoArea').value=area.id;$('photoTitle').value=ph.title||'';$('photoNote').value=ph.note||'';filter={brightness:100,contrast:100,saturation:100,sharpness:0};objects=[];history=[];future=[];selected=-1;loadURL(ph.data||ph.image,false);setTimeout(()=>{history=[];snap();},50)}function close(){editingPhoto=null;editingArea=null;modal.classList.add('hidden');modal.setAttribute('aria-hidden','true')}$('fpPhotoDocOpen')?.addEventListener('click',open);$('cadPdfReport')?.addEventListener('contextmenu',e=>{e.preventDefault();open()});$('photoClose').onclick=close;window.ProjectBauPhotoEditor={open,openExisting,close};gallery();
})();
